name: Update package versions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config url.https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf https://github.com/
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update versions
        run: bash bin/update-versions.sh

      - name: Commit and push changes
        run: |
          date +%m >.github/keep-alive
          git add .
          git commit -m "update versions"
          git push origin
